config/routes.rb
CommunityBoard::Application.routes.draw do
  use_doorkeeper

  devise_for :users
  resources :communities, except: :index do
    resources :posts
  end

  namespace "api" do
    namespace "v1" do
      resources :communities
    end
  end

  namespace "api" do
    namespace "v1" do
      resources :community do
        resources :posts
      end
    end
  end

  scope '/favourite' do
    resources :posts
  end

  scope '/subscribe' do
    resources :communities
  end

  root to: 'communities#index'
end

app/models/community.rb
class Community < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  belongs_to :owner, class_name: :User
  has_many :posts
  validates :name, presence: true
  validates :owner, presence: true

  def to_s
    name.to_s
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  belongs_to :community
  belongs_to :user

  validates :text, presence: true
  validates :user, presence: true
  validates :community, presence: true

  scope :new_to_old, -> { order("created_at desc") }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates :name, presence: true
  has_many :owned_communities, class_name: :Community, foreign_key: :owner_id

  def to_s
    name.to_s
  end

  def remember_me?
    true
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  private
  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/v1/communities_controller.rb
class Api::V1::CommunitiesController < ApplicationController
  respond_to :json
  def index
    @communities = Community.all
    respond_with @communities
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
doorkeeper_for :create
  respond_to :json

  def index
    @community = Community.find(params[:community_id])
    @posts = @community.posts.new_to_old
    respond_with @posts
  end

  def create
    @post = @community.posts.build(post_params)
    @post.user = current_resource_owner
    @post.save
    respond_with @post, location: nil
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_filter :authenticate_user!, only: %w[new create]
  before_filter :load_community, only: %w[show]
  respond_to :html

  def index
    @communities = Community.all
  end

  def new
    @community = current_user.owned_communities.new
  end

  def create
    @community = current_user.owned_communities.new(communitity_params)
    @community.save
    respond_with @community
  end

  private

  def load_community
    @community = Community.find(params[:id])
  end

  def communitity_params
    params.require(:community).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_community

  def create
    @post = @community.posts.new(post_params)
    @post.user = current_user
    @post.save
  end

  private

  def load_community
    @community = Community.find(params[:community_id])
  end

  def post_params
    params.require(:post).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/communities/index.html.haml
.hero-unit
  %h1 Community Board
  %p Created as an example for #{link_to "Client / Server Team-up: Pairing Ruby on Rails with iOS", "http://www.tokyorubyistmeetup.org/events/2814"}, an event organized by #{link_to "Tokyo iOS Meetup", "http://www.meetup.com/TokyoiOSMeetup/"} and #{link_to "Tokyo Rubyist Meetup", "http://www.tokyorubyistmeetup.org"}. Participants in the event will add a REST API to this Ruby on Rails application, and then modify an existing iPhone application to consume the API.
  %p The idea of the app itself is a simple message board, where people can post messages in different communities.
  - unless user_signed_in?
    %p
      = link_to "Login", new_user_session_path, class: "btn btn-primary"
      = link_to "Register", new_user_registration_path, class: "btn"

- (@communities + [:create_yours]).each_slice(4) do |row|
  .row
    - row.each do |c|
      .span3
        .community
          - if c == :create_yours
            .community-new= link_to "Create your own community!", new_community_path
          - else 
            = link_to c do
              = image_tag "https://lorempixel.com/500/350/?id=#{c.id}"
              .community-name
                %span= c.name
%small(style="margin-top: 20px; display: inline-block") Community photos are randomly generated from #{link_to "Lorem Pixel", "http://lorempixel.com/"}.

app/views/communities/new.html.haml
.page-header
  %h2 Create a new community
= simple_form_for @community, html: { class: "form-horizontal"} do |f|
  = f.input :name
  .form-actions
    = f.button :submit, "Create Community", class: "btn-primary"
    = link_to "Cancel", :back, class: "btn"

app/views/communities/show.html.haml
.alert.alert-error.hide#alert-placeholder
%ul.breadcrumb
  %li
    = link_to "Communities", root_path
    %span.divider /
  %li.active= @community

- if user_signed_in?
  = simple_form_for Post.new, url: community_posts_path(@community), remote: true do |f|
    .pull-right(style="width: 100px")= f.button :submit, "Post", class: "btn-primary", style: "width: 100%; height: 50px; vertical-align: top; font-size: 25px"
    %div(style="overflow: hidden; padding-right: 20px")= f.input :text, input_html: { rows: 2, style: "width: 100%" }, wrapper: :inline

#posts= render @community.posts.new_to_old

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Community Board"
    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"


  %body
    .github-fork-ribbon-wrapper.right-bottom
      .github-fork-ribbon
        = link_to "Fork me on GitHub", "https://github.com/rajmeenacse/community_board_rails"
    .navbar.navbar-static-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=root_path) Community Board
          .container.nav-collapse
            %ul.nav.pull-right
              - if user_signed_in?
                %li
                  = link_to edit_user_registration_path do
                    %i.icon-user
                    = current_user
                %li= link_to "Log out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Login", new_user_session_path

    .container#main
      = bootstrap_flash
      = yield
    
    = javascript_include_tag "application"

app/views/posts/_post.html.haml
.post
  = image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(post.user.email.downcase)}?s=50&d=mm", class: "avatar"
  .post-body
    = simple_format post.text
    %em Posted by #{post.user} #{distance_of_time_in_words_to_now(post.created_at)} ago

app/views/posts/create.js.erb
<% if @post.valid? %>
  $("#alert-placeholder").hide();
  $("#post_text").val("");
  $("#posts").prepend("<%= escape_javascript(render(@post)) =%>");
<% else %>
  $("#alert-placeholder").html("<%= escape_javascript(@post.errors.full_messages.join("\n"))%>");
  $("#alert-placeholder").show();
<% end %>

app/views/users/shared/_links.html.haml
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br

- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br